### PR TITLE
chore(minio): upgrading to the latest release

### PR DESCRIPTION
**Pull request by kingdonb**
For #6

### CODE REVIEW

**Comment by Cryptophobia** [comment]
Alright, I will merge this in right after you let me know how the test went. :+1:

**Review by Cryptophobia — APPROVED** [review]
lgtm

**Comment by kingdonb** [comment]
This is tested and works OK. I did not deal with the migration stuff, there may not even be any need.

I'll look into it, but this should be OK to merge as-is.  It's at `kingdonb/minio:canary`, I put it in my deployment and terminated the old pod... logged into the database, created the bucket again, ran `do_backup`

Then verified with `envdir "$WALE_ENVDIR" wal-e --terse backup-list` that the backup made it.

LGTM2

**Comment by Cryptophobia** [comment]
Alright sounds good! We will test again before next patch release.

**Review by Cryptophobia — APPROVED** [review]
lgtm

**Pull request merged**
